/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sinchana.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MessageType implements org.apache.thrift.TEnum {
  GET(0),
  JOIN(1),
  DISCOVER_NEIGHBOURS(2),
  FIND_SUCCESSOR(3),
  ERROR(4),
  ACCEPT(5),
  TEST_RING(6);

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MessageType findByValue(int value) { 
    switch (value) {
      case 0:
        return GET;
      case 1:
        return JOIN;
      case 2:
        return DISCOVER_NEIGHBOURS;
      case 3:
        return FIND_SUCCESSOR;
      case 4:
        return ERROR;
      case 5:
        return ACCEPT;
      case 6:
        return TEST_RING;
      default:
        return null;
    }
  }
}
