/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sinchana.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Message implements org.apache.thrift.TBase<Message, Message._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Message");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SOURCE_FIELD_DESC = new org.apache.thrift.protocol.TField("source", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField LIFETIME_FIELD_DESC = new org.apache.thrift.protocol.TField("lifetime", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField DESTINATION_FIELD_DESC = new org.apache.thrift.protocol.TField("destination", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField STATION_FIELD_DESC = new org.apache.thrift.protocol.TField("station", org.apache.thrift.protocol.TType.STRUCT, (short)6);
  private static final org.apache.thrift.protocol.TField DESTINATION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("destinationId", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("key", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("data", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField PREDECESSOR_FIELD_DESC = new org.apache.thrift.protocol.TField("predecessor", org.apache.thrift.protocol.TType.STRUCT, (short)10);
  private static final org.apache.thrift.protocol.TField SUCCESSOR_FIELD_DESC = new org.apache.thrift.protocol.TField("successor", org.apache.thrift.protocol.TType.STRUCT, (short)11);
  private static final org.apache.thrift.protocol.TField NEIGHBOUR_SET_FIELD_DESC = new org.apache.thrift.protocol.TField("neighbourSet", org.apache.thrift.protocol.TType.SET, (short)12);
  private static final org.apache.thrift.protocol.TField FAILED_NODE_SET_FIELD_DESC = new org.apache.thrift.protocol.TField("failedNodeSet", org.apache.thrift.protocol.TType.SET, (short)13);
  private static final org.apache.thrift.protocol.TField RETRY_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("retryCount", org.apache.thrift.protocol.TType.I32, (short)14);
  private static final org.apache.thrift.protocol.TField TIME_STAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timeStamp", org.apache.thrift.protocol.TType.I64, (short)15);
  private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.BOOL, (short)16);
  private static final org.apache.thrift.protocol.TField RESPONSE_EXPECTED_FIELD_DESC = new org.apache.thrift.protocol.TField("responseExpected", org.apache.thrift.protocol.TType.BOOL, (short)17);
  private static final org.apache.thrift.protocol.TField ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.STRING, (short)18);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MessageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MessageTupleSchemeFactory());
  }

  public long id; // optional
  public Node source; // required
  /**
   * 
   * @see MessageType
   */
  public MessageType type; // required
  public int lifetime; // required
  public Node destination; // optional
  public Node station; // optional
  public ByteBuffer destinationId; // optional
  public ByteBuffer key; // optional
  public ByteBuffer data; // optional
  public Node predecessor; // optional
  public Node successor; // optional
  public Set<Node> neighbourSet; // optional
  public Set<Node> failedNodeSet; // optional
  public int retryCount; // optional
  public long timeStamp; // optional
  public boolean success; // optional
  public boolean responseExpected; // optional
  public String error; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    SOURCE((short)2, "source"),
    /**
     * 
     * @see MessageType
     */
    TYPE((short)3, "type"),
    LIFETIME((short)4, "lifetime"),
    DESTINATION((short)5, "destination"),
    STATION((short)6, "station"),
    DESTINATION_ID((short)7, "destinationId"),
    KEY((short)8, "key"),
    DATA((short)9, "data"),
    PREDECESSOR((short)10, "predecessor"),
    SUCCESSOR((short)11, "successor"),
    NEIGHBOUR_SET((short)12, "neighbourSet"),
    FAILED_NODE_SET((short)13, "failedNodeSet"),
    RETRY_COUNT((short)14, "retryCount"),
    TIME_STAMP((short)15, "timeStamp"),
    SUCCESS((short)16, "success"),
    RESPONSE_EXPECTED((short)17, "responseExpected"),
    ERROR((short)18, "error");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // SOURCE
          return SOURCE;
        case 3: // TYPE
          return TYPE;
        case 4: // LIFETIME
          return LIFETIME;
        case 5: // DESTINATION
          return DESTINATION;
        case 6: // STATION
          return STATION;
        case 7: // DESTINATION_ID
          return DESTINATION_ID;
        case 8: // KEY
          return KEY;
        case 9: // DATA
          return DATA;
        case 10: // PREDECESSOR
          return PREDECESSOR;
        case 11: // SUCCESSOR
          return SUCCESSOR;
        case 12: // NEIGHBOUR_SET
          return NEIGHBOUR_SET;
        case 13: // FAILED_NODE_SET
          return FAILED_NODE_SET;
        case 14: // RETRY_COUNT
          return RETRY_COUNT;
        case 15: // TIME_STAMP
          return TIME_STAMP;
        case 16: // SUCCESS
          return SUCCESS;
        case 17: // RESPONSE_EXPECTED
          return RESPONSE_EXPECTED;
        case 18: // ERROR
          return ERROR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __LIFETIME_ISSET_ID = 1;
  private static final int __RETRYCOUNT_ISSET_ID = 2;
  private static final int __TIMESTAMP_ISSET_ID = 3;
  private static final int __SUCCESS_ISSET_ID = 4;
  private static final int __RESPONSEEXPECTED_ISSET_ID = 5;
  private BitSet __isset_bit_vector = new BitSet(6);
  private _Fields optionals[] = {_Fields.ID,_Fields.DESTINATION,_Fields.STATION,_Fields.DESTINATION_ID,_Fields.KEY,_Fields.DATA,_Fields.PREDECESSOR,_Fields.SUCCESSOR,_Fields.NEIGHBOUR_SET,_Fields.FAILED_NODE_SET,_Fields.RETRY_COUNT,_Fields.TIME_STAMP,_Fields.SUCCESS,_Fields.RESPONSE_EXPECTED,_Fields.ERROR};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SOURCE, new org.apache.thrift.meta_data.FieldMetaData("source", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Node.class)));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, MessageType.class)));
    tmpMap.put(_Fields.LIFETIME, new org.apache.thrift.meta_data.FieldMetaData("lifetime", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DESTINATION, new org.apache.thrift.meta_data.FieldMetaData("destination", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Node.class)));
    tmpMap.put(_Fields.STATION, new org.apache.thrift.meta_data.FieldMetaData("station", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Node.class)));
    tmpMap.put(_Fields.DESTINATION_ID, new org.apache.thrift.meta_data.FieldMetaData("destinationId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.KEY, new org.apache.thrift.meta_data.FieldMetaData("key", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.DATA, new org.apache.thrift.meta_data.FieldMetaData("data", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.PREDECESSOR, new org.apache.thrift.meta_data.FieldMetaData("predecessor", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Node.class)));
    tmpMap.put(_Fields.SUCCESSOR, new org.apache.thrift.meta_data.FieldMetaData("successor", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Node.class)));
    tmpMap.put(_Fields.NEIGHBOUR_SET, new org.apache.thrift.meta_data.FieldMetaData("neighbourSet", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Node.class))));
    tmpMap.put(_Fields.FAILED_NODE_SET, new org.apache.thrift.meta_data.FieldMetaData("failedNodeSet", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Node.class))));
    tmpMap.put(_Fields.RETRY_COUNT, new org.apache.thrift.meta_data.FieldMetaData("retryCount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TIME_STAMP, new org.apache.thrift.meta_data.FieldMetaData("timeStamp", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.RESPONSE_EXPECTED, new org.apache.thrift.meta_data.FieldMetaData("responseExpected", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ERROR, new org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Message.class, metaDataMap);
  }

  public Message() {
  }

  public Message(
    Node source,
    MessageType type,
    int lifetime)
  {
    this();
    this.source = source;
    this.type = type;
    this.lifetime = lifetime;
    setLifetimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Message(Message other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.id = other.id;
    if (other.isSetSource()) {
      this.source = new Node(other.source);
    }
    if (other.isSetType()) {
      this.type = other.type;
    }
    this.lifetime = other.lifetime;
    if (other.isSetDestination()) {
      this.destination = new Node(other.destination);
    }
    if (other.isSetStation()) {
      this.station = new Node(other.station);
    }
    if (other.isSetDestinationId()) {
      this.destinationId = org.apache.thrift.TBaseHelper.copyBinary(other.destinationId);
;
    }
    if (other.isSetKey()) {
      this.key = org.apache.thrift.TBaseHelper.copyBinary(other.key);
;
    }
    if (other.isSetData()) {
      this.data = org.apache.thrift.TBaseHelper.copyBinary(other.data);
;
    }
    if (other.isSetPredecessor()) {
      this.predecessor = new Node(other.predecessor);
    }
    if (other.isSetSuccessor()) {
      this.successor = new Node(other.successor);
    }
    if (other.isSetNeighbourSet()) {
      Set<Node> __this__neighbourSet = new HashSet<Node>();
      for (Node other_element : other.neighbourSet) {
        __this__neighbourSet.add(new Node(other_element));
      }
      this.neighbourSet = __this__neighbourSet;
    }
    if (other.isSetFailedNodeSet()) {
      Set<Node> __this__failedNodeSet = new HashSet<Node>();
      for (Node other_element : other.failedNodeSet) {
        __this__failedNodeSet.add(new Node(other_element));
      }
      this.failedNodeSet = __this__failedNodeSet;
    }
    this.retryCount = other.retryCount;
    this.timeStamp = other.timeStamp;
    this.success = other.success;
    this.responseExpected = other.responseExpected;
    if (other.isSetError()) {
      this.error = other.error;
    }
  }

  public Message deepCopy() {
    return new Message(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.source = null;
    this.type = null;
    setLifetimeIsSet(false);
    this.lifetime = 0;
    this.destination = null;
    this.station = null;
    this.destinationId = null;
    this.key = null;
    this.data = null;
    this.predecessor = null;
    this.successor = null;
    this.neighbourSet = null;
    this.failedNodeSet = null;
    setRetryCountIsSet(false);
    this.retryCount = 0;
    setTimeStampIsSet(false);
    this.timeStamp = 0;
    setSuccessIsSet(false);
    this.success = false;
    setResponseExpectedIsSet(false);
    this.responseExpected = false;
    this.error = null;
  }

  public long getId() {
    return this.id;
  }

  public Message setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bit_vector.clear(__ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return __isset_bit_vector.get(__ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bit_vector.set(__ID_ISSET_ID, value);
  }

  public Node getSource() {
    return this.source;
  }

  public Message setSource(Node source) {
    this.source = source;
    return this;
  }

  public void unsetSource() {
    this.source = null;
  }

  /** Returns true if field source is set (has been assigned a value) and false otherwise */
  public boolean isSetSource() {
    return this.source != null;
  }

  public void setSourceIsSet(boolean value) {
    if (!value) {
      this.source = null;
    }
  }

  /**
   * 
   * @see MessageType
   */
  public MessageType getType() {
    return this.type;
  }

  /**
   * 
   * @see MessageType
   */
  public Message setType(MessageType type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  public int getLifetime() {
    return this.lifetime;
  }

  public Message setLifetime(int lifetime) {
    this.lifetime = lifetime;
    setLifetimeIsSet(true);
    return this;
  }

  public void unsetLifetime() {
    __isset_bit_vector.clear(__LIFETIME_ISSET_ID);
  }

  /** Returns true if field lifetime is set (has been assigned a value) and false otherwise */
  public boolean isSetLifetime() {
    return __isset_bit_vector.get(__LIFETIME_ISSET_ID);
  }

  public void setLifetimeIsSet(boolean value) {
    __isset_bit_vector.set(__LIFETIME_ISSET_ID, value);
  }

  public Node getDestination() {
    return this.destination;
  }

  public Message setDestination(Node destination) {
    this.destination = destination;
    return this;
  }

  public void unsetDestination() {
    this.destination = null;
  }

  /** Returns true if field destination is set (has been assigned a value) and false otherwise */
  public boolean isSetDestination() {
    return this.destination != null;
  }

  public void setDestinationIsSet(boolean value) {
    if (!value) {
      this.destination = null;
    }
  }

  public Node getStation() {
    return this.station;
  }

  public Message setStation(Node station) {
    this.station = station;
    return this;
  }

  public void unsetStation() {
    this.station = null;
  }

  /** Returns true if field station is set (has been assigned a value) and false otherwise */
  public boolean isSetStation() {
    return this.station != null;
  }

  public void setStationIsSet(boolean value) {
    if (!value) {
      this.station = null;
    }
  }

  public byte[] getDestinationId() {
    setDestinationId(org.apache.thrift.TBaseHelper.rightSize(destinationId));
    return destinationId == null ? null : destinationId.array();
  }

  public ByteBuffer bufferForDestinationId() {
    return destinationId;
  }

  public Message setDestinationId(byte[] destinationId) {
    setDestinationId(destinationId == null ? (ByteBuffer)null : ByteBuffer.wrap(destinationId));
    return this;
  }

  public Message setDestinationId(ByteBuffer destinationId) {
    this.destinationId = destinationId;
    return this;
  }

  public void unsetDestinationId() {
    this.destinationId = null;
  }

  /** Returns true if field destinationId is set (has been assigned a value) and false otherwise */
  public boolean isSetDestinationId() {
    return this.destinationId != null;
  }

  public void setDestinationIdIsSet(boolean value) {
    if (!value) {
      this.destinationId = null;
    }
  }

  public byte[] getKey() {
    setKey(org.apache.thrift.TBaseHelper.rightSize(key));
    return key == null ? null : key.array();
  }

  public ByteBuffer bufferForKey() {
    return key;
  }

  public Message setKey(byte[] key) {
    setKey(key == null ? (ByteBuffer)null : ByteBuffer.wrap(key));
    return this;
  }

  public Message setKey(ByteBuffer key) {
    this.key = key;
    return this;
  }

  public void unsetKey() {
    this.key = null;
  }

  /** Returns true if field key is set (has been assigned a value) and false otherwise */
  public boolean isSetKey() {
    return this.key != null;
  }

  public void setKeyIsSet(boolean value) {
    if (!value) {
      this.key = null;
    }
  }

  public byte[] getData() {
    setData(org.apache.thrift.TBaseHelper.rightSize(data));
    return data == null ? null : data.array();
  }

  public ByteBuffer bufferForData() {
    return data;
  }

  public Message setData(byte[] data) {
    setData(data == null ? (ByteBuffer)null : ByteBuffer.wrap(data));
    return this;
  }

  public Message setData(ByteBuffer data) {
    this.data = data;
    return this;
  }

  public void unsetData() {
    this.data = null;
  }

  /** Returns true if field data is set (has been assigned a value) and false otherwise */
  public boolean isSetData() {
    return this.data != null;
  }

  public void setDataIsSet(boolean value) {
    if (!value) {
      this.data = null;
    }
  }

  public Node getPredecessor() {
    return this.predecessor;
  }

  public Message setPredecessor(Node predecessor) {
    this.predecessor = predecessor;
    return this;
  }

  public void unsetPredecessor() {
    this.predecessor = null;
  }

  /** Returns true if field predecessor is set (has been assigned a value) and false otherwise */
  public boolean isSetPredecessor() {
    return this.predecessor != null;
  }

  public void setPredecessorIsSet(boolean value) {
    if (!value) {
      this.predecessor = null;
    }
  }

  public Node getSuccessor() {
    return this.successor;
  }

  public Message setSuccessor(Node successor) {
    this.successor = successor;
    return this;
  }

  public void unsetSuccessor() {
    this.successor = null;
  }

  /** Returns true if field successor is set (has been assigned a value) and false otherwise */
  public boolean isSetSuccessor() {
    return this.successor != null;
  }

  public void setSuccessorIsSet(boolean value) {
    if (!value) {
      this.successor = null;
    }
  }

  public int getNeighbourSetSize() {
    return (this.neighbourSet == null) ? 0 : this.neighbourSet.size();
  }

  public java.util.Iterator<Node> getNeighbourSetIterator() {
    return (this.neighbourSet == null) ? null : this.neighbourSet.iterator();
  }

  public void addToNeighbourSet(Node elem) {
    if (this.neighbourSet == null) {
      this.neighbourSet = new HashSet<Node>();
    }
    this.neighbourSet.add(elem);
  }

  public Set<Node> getNeighbourSet() {
    return this.neighbourSet;
  }

  public Message setNeighbourSet(Set<Node> neighbourSet) {
    this.neighbourSet = neighbourSet;
    return this;
  }

  public void unsetNeighbourSet() {
    this.neighbourSet = null;
  }

  /** Returns true if field neighbourSet is set (has been assigned a value) and false otherwise */
  public boolean isSetNeighbourSet() {
    return this.neighbourSet != null;
  }

  public void setNeighbourSetIsSet(boolean value) {
    if (!value) {
      this.neighbourSet = null;
    }
  }

  public int getFailedNodeSetSize() {
    return (this.failedNodeSet == null) ? 0 : this.failedNodeSet.size();
  }

  public java.util.Iterator<Node> getFailedNodeSetIterator() {
    return (this.failedNodeSet == null) ? null : this.failedNodeSet.iterator();
  }

  public void addToFailedNodeSet(Node elem) {
    if (this.failedNodeSet == null) {
      this.failedNodeSet = new HashSet<Node>();
    }
    this.failedNodeSet.add(elem);
  }

  public Set<Node> getFailedNodeSet() {
    return this.failedNodeSet;
  }

  public Message setFailedNodeSet(Set<Node> failedNodeSet) {
    this.failedNodeSet = failedNodeSet;
    return this;
  }

  public void unsetFailedNodeSet() {
    this.failedNodeSet = null;
  }

  /** Returns true if field failedNodeSet is set (has been assigned a value) and false otherwise */
  public boolean isSetFailedNodeSet() {
    return this.failedNodeSet != null;
  }

  public void setFailedNodeSetIsSet(boolean value) {
    if (!value) {
      this.failedNodeSet = null;
    }
  }

  public int getRetryCount() {
    return this.retryCount;
  }

  public Message setRetryCount(int retryCount) {
    this.retryCount = retryCount;
    setRetryCountIsSet(true);
    return this;
  }

  public void unsetRetryCount() {
    __isset_bit_vector.clear(__RETRYCOUNT_ISSET_ID);
  }

  /** Returns true if field retryCount is set (has been assigned a value) and false otherwise */
  public boolean isSetRetryCount() {
    return __isset_bit_vector.get(__RETRYCOUNT_ISSET_ID);
  }

  public void setRetryCountIsSet(boolean value) {
    __isset_bit_vector.set(__RETRYCOUNT_ISSET_ID, value);
  }

  public long getTimeStamp() {
    return this.timeStamp;
  }

  public Message setTimeStamp(long timeStamp) {
    this.timeStamp = timeStamp;
    setTimeStampIsSet(true);
    return this;
  }

  public void unsetTimeStamp() {
    __isset_bit_vector.clear(__TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timeStamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimeStamp() {
    return __isset_bit_vector.get(__TIMESTAMP_ISSET_ID);
  }

  public void setTimeStampIsSet(boolean value) {
    __isset_bit_vector.set(__TIMESTAMP_ISSET_ID, value);
  }

  public boolean isSuccess() {
    return this.success;
  }

  public Message setSuccess(boolean success) {
    this.success = success;
    setSuccessIsSet(true);
    return this;
  }

  public void unsetSuccess() {
    __isset_bit_vector.clear(__SUCCESS_ISSET_ID);
  }

  /** Returns true if field success is set (has been assigned a value) and false otherwise */
  public boolean isSetSuccess() {
    return __isset_bit_vector.get(__SUCCESS_ISSET_ID);
  }

  public void setSuccessIsSet(boolean value) {
    __isset_bit_vector.set(__SUCCESS_ISSET_ID, value);
  }

  public boolean isResponseExpected() {
    return this.responseExpected;
  }

  public Message setResponseExpected(boolean responseExpected) {
    this.responseExpected = responseExpected;
    setResponseExpectedIsSet(true);
    return this;
  }

  public void unsetResponseExpected() {
    __isset_bit_vector.clear(__RESPONSEEXPECTED_ISSET_ID);
  }

  /** Returns true if field responseExpected is set (has been assigned a value) and false otherwise */
  public boolean isSetResponseExpected() {
    return __isset_bit_vector.get(__RESPONSEEXPECTED_ISSET_ID);
  }

  public void setResponseExpectedIsSet(boolean value) {
    __isset_bit_vector.set(__RESPONSEEXPECTED_ISSET_ID, value);
  }

  public String getError() {
    return this.error;
  }

  public Message setError(String error) {
    this.error = error;
    return this;
  }

  public void unsetError() {
    this.error = null;
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  public boolean isSetError() {
    return this.error != null;
  }

  public void setErrorIsSet(boolean value) {
    if (!value) {
      this.error = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Long)value);
      }
      break;

    case SOURCE:
      if (value == null) {
        unsetSource();
      } else {
        setSource((Node)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((MessageType)value);
      }
      break;

    case LIFETIME:
      if (value == null) {
        unsetLifetime();
      } else {
        setLifetime((Integer)value);
      }
      break;

    case DESTINATION:
      if (value == null) {
        unsetDestination();
      } else {
        setDestination((Node)value);
      }
      break;

    case STATION:
      if (value == null) {
        unsetStation();
      } else {
        setStation((Node)value);
      }
      break;

    case DESTINATION_ID:
      if (value == null) {
        unsetDestinationId();
      } else {
        setDestinationId((ByteBuffer)value);
      }
      break;

    case KEY:
      if (value == null) {
        unsetKey();
      } else {
        setKey((ByteBuffer)value);
      }
      break;

    case DATA:
      if (value == null) {
        unsetData();
      } else {
        setData((ByteBuffer)value);
      }
      break;

    case PREDECESSOR:
      if (value == null) {
        unsetPredecessor();
      } else {
        setPredecessor((Node)value);
      }
      break;

    case SUCCESSOR:
      if (value == null) {
        unsetSuccessor();
      } else {
        setSuccessor((Node)value);
      }
      break;

    case NEIGHBOUR_SET:
      if (value == null) {
        unsetNeighbourSet();
      } else {
        setNeighbourSet((Set<Node>)value);
      }
      break;

    case FAILED_NODE_SET:
      if (value == null) {
        unsetFailedNodeSet();
      } else {
        setFailedNodeSet((Set<Node>)value);
      }
      break;

    case RETRY_COUNT:
      if (value == null) {
        unsetRetryCount();
      } else {
        setRetryCount((Integer)value);
      }
      break;

    case TIME_STAMP:
      if (value == null) {
        unsetTimeStamp();
      } else {
        setTimeStamp((Long)value);
      }
      break;

    case SUCCESS:
      if (value == null) {
        unsetSuccess();
      } else {
        setSuccess((Boolean)value);
      }
      break;

    case RESPONSE_EXPECTED:
      if (value == null) {
        unsetResponseExpected();
      } else {
        setResponseExpected((Boolean)value);
      }
      break;

    case ERROR:
      if (value == null) {
        unsetError();
      } else {
        setError((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return Long.valueOf(getId());

    case SOURCE:
      return getSource();

    case TYPE:
      return getType();

    case LIFETIME:
      return Integer.valueOf(getLifetime());

    case DESTINATION:
      return getDestination();

    case STATION:
      return getStation();

    case DESTINATION_ID:
      return getDestinationId();

    case KEY:
      return getKey();

    case DATA:
      return getData();

    case PREDECESSOR:
      return getPredecessor();

    case SUCCESSOR:
      return getSuccessor();

    case NEIGHBOUR_SET:
      return getNeighbourSet();

    case FAILED_NODE_SET:
      return getFailedNodeSet();

    case RETRY_COUNT:
      return Integer.valueOf(getRetryCount());

    case TIME_STAMP:
      return Long.valueOf(getTimeStamp());

    case SUCCESS:
      return Boolean.valueOf(isSuccess());

    case RESPONSE_EXPECTED:
      return Boolean.valueOf(isResponseExpected());

    case ERROR:
      return getError();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case SOURCE:
      return isSetSource();
    case TYPE:
      return isSetType();
    case LIFETIME:
      return isSetLifetime();
    case DESTINATION:
      return isSetDestination();
    case STATION:
      return isSetStation();
    case DESTINATION_ID:
      return isSetDestinationId();
    case KEY:
      return isSetKey();
    case DATA:
      return isSetData();
    case PREDECESSOR:
      return isSetPredecessor();
    case SUCCESSOR:
      return isSetSuccessor();
    case NEIGHBOUR_SET:
      return isSetNeighbourSet();
    case FAILED_NODE_SET:
      return isSetFailedNodeSet();
    case RETRY_COUNT:
      return isSetRetryCount();
    case TIME_STAMP:
      return isSetTimeStamp();
    case SUCCESS:
      return isSetSuccess();
    case RESPONSE_EXPECTED:
      return isSetResponseExpected();
    case ERROR:
      return isSetError();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Message)
      return this.equals((Message)that);
    return false;
  }

  public boolean equals(Message that) {
    if (that == null)
      return false;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_source = true && this.isSetSource();
    boolean that_present_source = true && that.isSetSource();
    if (this_present_source || that_present_source) {
      if (!(this_present_source && that_present_source))
        return false;
      if (!this.source.equals(that.source))
        return false;
    }

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_lifetime = true;
    boolean that_present_lifetime = true;
    if (this_present_lifetime || that_present_lifetime) {
      if (!(this_present_lifetime && that_present_lifetime))
        return false;
      if (this.lifetime != that.lifetime)
        return false;
    }

    boolean this_present_destination = true && this.isSetDestination();
    boolean that_present_destination = true && that.isSetDestination();
    if (this_present_destination || that_present_destination) {
      if (!(this_present_destination && that_present_destination))
        return false;
      if (!this.destination.equals(that.destination))
        return false;
    }

    boolean this_present_station = true && this.isSetStation();
    boolean that_present_station = true && that.isSetStation();
    if (this_present_station || that_present_station) {
      if (!(this_present_station && that_present_station))
        return false;
      if (!this.station.equals(that.station))
        return false;
    }

    boolean this_present_destinationId = true && this.isSetDestinationId();
    boolean that_present_destinationId = true && that.isSetDestinationId();
    if (this_present_destinationId || that_present_destinationId) {
      if (!(this_present_destinationId && that_present_destinationId))
        return false;
      if (!this.destinationId.equals(that.destinationId))
        return false;
    }

    boolean this_present_key = true && this.isSetKey();
    boolean that_present_key = true && that.isSetKey();
    if (this_present_key || that_present_key) {
      if (!(this_present_key && that_present_key))
        return false;
      if (!this.key.equals(that.key))
        return false;
    }

    boolean this_present_data = true && this.isSetData();
    boolean that_present_data = true && that.isSetData();
    if (this_present_data || that_present_data) {
      if (!(this_present_data && that_present_data))
        return false;
      if (!this.data.equals(that.data))
        return false;
    }

    boolean this_present_predecessor = true && this.isSetPredecessor();
    boolean that_present_predecessor = true && that.isSetPredecessor();
    if (this_present_predecessor || that_present_predecessor) {
      if (!(this_present_predecessor && that_present_predecessor))
        return false;
      if (!this.predecessor.equals(that.predecessor))
        return false;
    }

    boolean this_present_successor = true && this.isSetSuccessor();
    boolean that_present_successor = true && that.isSetSuccessor();
    if (this_present_successor || that_present_successor) {
      if (!(this_present_successor && that_present_successor))
        return false;
      if (!this.successor.equals(that.successor))
        return false;
    }

    boolean this_present_neighbourSet = true && this.isSetNeighbourSet();
    boolean that_present_neighbourSet = true && that.isSetNeighbourSet();
    if (this_present_neighbourSet || that_present_neighbourSet) {
      if (!(this_present_neighbourSet && that_present_neighbourSet))
        return false;
      if (!this.neighbourSet.equals(that.neighbourSet))
        return false;
    }

    boolean this_present_failedNodeSet = true && this.isSetFailedNodeSet();
    boolean that_present_failedNodeSet = true && that.isSetFailedNodeSet();
    if (this_present_failedNodeSet || that_present_failedNodeSet) {
      if (!(this_present_failedNodeSet && that_present_failedNodeSet))
        return false;
      if (!this.failedNodeSet.equals(that.failedNodeSet))
        return false;
    }

    boolean this_present_retryCount = true && this.isSetRetryCount();
    boolean that_present_retryCount = true && that.isSetRetryCount();
    if (this_present_retryCount || that_present_retryCount) {
      if (!(this_present_retryCount && that_present_retryCount))
        return false;
      if (this.retryCount != that.retryCount)
        return false;
    }

    boolean this_present_timeStamp = true && this.isSetTimeStamp();
    boolean that_present_timeStamp = true && that.isSetTimeStamp();
    if (this_present_timeStamp || that_present_timeStamp) {
      if (!(this_present_timeStamp && that_present_timeStamp))
        return false;
      if (this.timeStamp != that.timeStamp)
        return false;
    }

    boolean this_present_success = true && this.isSetSuccess();
    boolean that_present_success = true && that.isSetSuccess();
    if (this_present_success || that_present_success) {
      if (!(this_present_success && that_present_success))
        return false;
      if (this.success != that.success)
        return false;
    }

    boolean this_present_responseExpected = true && this.isSetResponseExpected();
    boolean that_present_responseExpected = true && that.isSetResponseExpected();
    if (this_present_responseExpected || that_present_responseExpected) {
      if (!(this_present_responseExpected && that_present_responseExpected))
        return false;
      if (this.responseExpected != that.responseExpected)
        return false;
    }

    boolean this_present_error = true && this.isSetError();
    boolean that_present_error = true && that.isSetError();
    if (this_present_error || that_present_error) {
      if (!(this_present_error && that_present_error))
        return false;
      if (!this.error.equals(that.error))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Message other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Message typedOther = (Message)other;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, typedOther.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSource()).compareTo(typedOther.isSetSource());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSource()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.source, typedOther.source);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetType()).compareTo(typedOther.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, typedOther.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLifetime()).compareTo(typedOther.isSetLifetime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLifetime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lifetime, typedOther.lifetime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDestination()).compareTo(typedOther.isSetDestination());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestination()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destination, typedOther.destination);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStation()).compareTo(typedOther.isSetStation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.station, typedOther.station);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDestinationId()).compareTo(typedOther.isSetDestinationId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestinationId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destinationId, typedOther.destinationId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetKey()).compareTo(typedOther.isSetKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.key, typedOther.key);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetData()).compareTo(typedOther.isSetData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.data, typedOther.data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPredecessor()).compareTo(typedOther.isSetPredecessor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPredecessor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.predecessor, typedOther.predecessor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSuccessor()).compareTo(typedOther.isSetSuccessor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuccessor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.successor, typedOther.successor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNeighbourSet()).compareTo(typedOther.isSetNeighbourSet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNeighbourSet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.neighbourSet, typedOther.neighbourSet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFailedNodeSet()).compareTo(typedOther.isSetFailedNodeSet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFailedNodeSet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.failedNodeSet, typedOther.failedNodeSet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRetryCount()).compareTo(typedOther.isSetRetryCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRetryCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.retryCount, typedOther.retryCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTimeStamp()).compareTo(typedOther.isSetTimeStamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimeStamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timeStamp, typedOther.timeStamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuccess()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResponseExpected()).compareTo(typedOther.isSetResponseExpected());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponseExpected()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.responseExpected, typedOther.responseExpected);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetError()).compareTo(typedOther.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, typedOther.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Message(");
    boolean first = true;

    if (isSetId()) {
      sb.append("id:");
      sb.append(this.id);
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("source:");
    if (this.source == null) {
      sb.append("null");
    } else {
      sb.append(this.source);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("lifetime:");
    sb.append(this.lifetime);
    first = false;
    if (isSetDestination()) {
      if (!first) sb.append(", ");
      sb.append("destination:");
      if (this.destination == null) {
        sb.append("null");
      } else {
        sb.append(this.destination);
      }
      first = false;
    }
    if (isSetStation()) {
      if (!first) sb.append(", ");
      sb.append("station:");
      if (this.station == null) {
        sb.append("null");
      } else {
        sb.append(this.station);
      }
      first = false;
    }
    if (isSetDestinationId()) {
      if (!first) sb.append(", ");
      sb.append("destinationId:");
      if (this.destinationId == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.destinationId, sb);
      }
      first = false;
    }
    if (isSetKey()) {
      if (!first) sb.append(", ");
      sb.append("key:");
      if (this.key == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.key, sb);
      }
      first = false;
    }
    if (isSetData()) {
      if (!first) sb.append(", ");
      sb.append("data:");
      if (this.data == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.data, sb);
      }
      first = false;
    }
    if (isSetPredecessor()) {
      if (!first) sb.append(", ");
      sb.append("predecessor:");
      if (this.predecessor == null) {
        sb.append("null");
      } else {
        sb.append(this.predecessor);
      }
      first = false;
    }
    if (isSetSuccessor()) {
      if (!first) sb.append(", ");
      sb.append("successor:");
      if (this.successor == null) {
        sb.append("null");
      } else {
        sb.append(this.successor);
      }
      first = false;
    }
    if (isSetNeighbourSet()) {
      if (!first) sb.append(", ");
      sb.append("neighbourSet:");
      if (this.neighbourSet == null) {
        sb.append("null");
      } else {
        sb.append(this.neighbourSet);
      }
      first = false;
    }
    if (isSetFailedNodeSet()) {
      if (!first) sb.append(", ");
      sb.append("failedNodeSet:");
      if (this.failedNodeSet == null) {
        sb.append("null");
      } else {
        sb.append(this.failedNodeSet);
      }
      first = false;
    }
    if (isSetRetryCount()) {
      if (!first) sb.append(", ");
      sb.append("retryCount:");
      sb.append(this.retryCount);
      first = false;
    }
    if (isSetTimeStamp()) {
      if (!first) sb.append(", ");
      sb.append("timeStamp:");
      sb.append(this.timeStamp);
      first = false;
    }
    if (isSetSuccess()) {
      if (!first) sb.append(", ");
      sb.append("success:");
      sb.append(this.success);
      first = false;
    }
    if (isSetResponseExpected()) {
      if (!first) sb.append(", ");
      sb.append("responseExpected:");
      sb.append(this.responseExpected);
      first = false;
    }
    if (isSetError()) {
      if (!first) sb.append(", ");
      sb.append("error:");
      if (this.error == null) {
        sb.append("null");
      } else {
        sb.append(this.error);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (source == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'source' was not present! Struct: " + toString());
    }
    if (type == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'type' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'lifetime' because it's a primitive and you chose the non-beans generator.
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MessageStandardSchemeFactory implements SchemeFactory {
    public MessageStandardScheme getScheme() {
      return new MessageStandardScheme();
    }
  }

  private static class MessageStandardScheme extends StandardScheme<Message> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Message struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SOURCE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.source = new Node();
              struct.source.read(iprot);
              struct.setSourceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = MessageType.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LIFETIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.lifetime = iprot.readI32();
              struct.setLifetimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // DESTINATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.destination = new Node();
              struct.destination.read(iprot);
              struct.setDestinationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // STATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.station = new Node();
              struct.station.read(iprot);
              struct.setStationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DESTINATION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.destinationId = iprot.readBinary();
              struct.setDestinationIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.key = iprot.readBinary();
              struct.setKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.data = iprot.readBinary();
              struct.setDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // PREDECESSOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.predecessor = new Node();
              struct.predecessor.read(iprot);
              struct.setPredecessorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // SUCCESSOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.successor = new Node();
              struct.successor.read(iprot);
              struct.setSuccessorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // NEIGHBOUR_SET
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set0 = iprot.readSetBegin();
                struct.neighbourSet = new HashSet<Node>(2*_set0.size);
                for (int _i1 = 0; _i1 < _set0.size; ++_i1)
                {
                  Node _elem2; // required
                  _elem2 = new Node();
                  _elem2.read(iprot);
                  struct.neighbourSet.add(_elem2);
                }
                iprot.readSetEnd();
              }
              struct.setNeighbourSetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // FAILED_NODE_SET
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set3 = iprot.readSetBegin();
                struct.failedNodeSet = new HashSet<Node>(2*_set3.size);
                for (int _i4 = 0; _i4 < _set3.size; ++_i4)
                {
                  Node _elem5; // required
                  _elem5 = new Node();
                  _elem5.read(iprot);
                  struct.failedNodeSet.add(_elem5);
                }
                iprot.readSetEnd();
              }
              struct.setFailedNodeSetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // RETRY_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.retryCount = iprot.readI32();
              struct.setRetryCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // TIME_STAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timeStamp = iprot.readI64();
              struct.setTimeStampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // SUCCESS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.success = iprot.readBool();
              struct.setSuccessIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // RESPONSE_EXPECTED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.responseExpected = iprot.readBool();
              struct.setResponseExpectedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 18: // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.error = iprot.readString();
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetLifetime()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'lifetime' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Message struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetId()) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeI64(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.source != null) {
        oprot.writeFieldBegin(SOURCE_FIELD_DESC);
        struct.source.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LIFETIME_FIELD_DESC);
      oprot.writeI32(struct.lifetime);
      oprot.writeFieldEnd();
      if (struct.destination != null) {
        if (struct.isSetDestination()) {
          oprot.writeFieldBegin(DESTINATION_FIELD_DESC);
          struct.destination.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.station != null) {
        if (struct.isSetStation()) {
          oprot.writeFieldBegin(STATION_FIELD_DESC);
          struct.station.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.destinationId != null) {
        if (struct.isSetDestinationId()) {
          oprot.writeFieldBegin(DESTINATION_ID_FIELD_DESC);
          oprot.writeBinary(struct.destinationId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.key != null) {
        if (struct.isSetKey()) {
          oprot.writeFieldBegin(KEY_FIELD_DESC);
          oprot.writeBinary(struct.key);
          oprot.writeFieldEnd();
        }
      }
      if (struct.data != null) {
        if (struct.isSetData()) {
          oprot.writeFieldBegin(DATA_FIELD_DESC);
          oprot.writeBinary(struct.data);
          oprot.writeFieldEnd();
        }
      }
      if (struct.predecessor != null) {
        if (struct.isSetPredecessor()) {
          oprot.writeFieldBegin(PREDECESSOR_FIELD_DESC);
          struct.predecessor.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.successor != null) {
        if (struct.isSetSuccessor()) {
          oprot.writeFieldBegin(SUCCESSOR_FIELD_DESC);
          struct.successor.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.neighbourSet != null) {
        if (struct.isSetNeighbourSet()) {
          oprot.writeFieldBegin(NEIGHBOUR_SET_FIELD_DESC);
          {
            oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.neighbourSet.size()));
            for (Node _iter6 : struct.neighbourSet)
            {
              _iter6.write(oprot);
            }
            oprot.writeSetEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.failedNodeSet != null) {
        if (struct.isSetFailedNodeSet()) {
          oprot.writeFieldBegin(FAILED_NODE_SET_FIELD_DESC);
          {
            oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.failedNodeSet.size()));
            for (Node _iter7 : struct.failedNodeSet)
            {
              _iter7.write(oprot);
            }
            oprot.writeSetEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetRetryCount()) {
        oprot.writeFieldBegin(RETRY_COUNT_FIELD_DESC);
        oprot.writeI32(struct.retryCount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetTimeStamp()) {
        oprot.writeFieldBegin(TIME_STAMP_FIELD_DESC);
        oprot.writeI64(struct.timeStamp);
        oprot.writeFieldEnd();
      }
      if (struct.isSetSuccess()) {
        oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
        oprot.writeBool(struct.success);
        oprot.writeFieldEnd();
      }
      if (struct.isSetResponseExpected()) {
        oprot.writeFieldBegin(RESPONSE_EXPECTED_FIELD_DESC);
        oprot.writeBool(struct.responseExpected);
        oprot.writeFieldEnd();
      }
      if (struct.error != null) {
        if (struct.isSetError()) {
          oprot.writeFieldBegin(ERROR_FIELD_DESC);
          oprot.writeString(struct.error);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MessageTupleSchemeFactory implements SchemeFactory {
    public MessageTupleScheme getScheme() {
      return new MessageTupleScheme();
    }
  }

  private static class MessageTupleScheme extends TupleScheme<Message> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Message struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.source.write(oprot);
      oprot.writeI32(struct.type.getValue());
      oprot.writeI32(struct.lifetime);
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetDestination()) {
        optionals.set(1);
      }
      if (struct.isSetStation()) {
        optionals.set(2);
      }
      if (struct.isSetDestinationId()) {
        optionals.set(3);
      }
      if (struct.isSetKey()) {
        optionals.set(4);
      }
      if (struct.isSetData()) {
        optionals.set(5);
      }
      if (struct.isSetPredecessor()) {
        optionals.set(6);
      }
      if (struct.isSetSuccessor()) {
        optionals.set(7);
      }
      if (struct.isSetNeighbourSet()) {
        optionals.set(8);
      }
      if (struct.isSetFailedNodeSet()) {
        optionals.set(9);
      }
      if (struct.isSetRetryCount()) {
        optionals.set(10);
      }
      if (struct.isSetTimeStamp()) {
        optionals.set(11);
      }
      if (struct.isSetSuccess()) {
        optionals.set(12);
      }
      if (struct.isSetResponseExpected()) {
        optionals.set(13);
      }
      if (struct.isSetError()) {
        optionals.set(14);
      }
      oprot.writeBitSet(optionals, 15);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetDestination()) {
        struct.destination.write(oprot);
      }
      if (struct.isSetStation()) {
        struct.station.write(oprot);
      }
      if (struct.isSetDestinationId()) {
        oprot.writeBinary(struct.destinationId);
      }
      if (struct.isSetKey()) {
        oprot.writeBinary(struct.key);
      }
      if (struct.isSetData()) {
        oprot.writeBinary(struct.data);
      }
      if (struct.isSetPredecessor()) {
        struct.predecessor.write(oprot);
      }
      if (struct.isSetSuccessor()) {
        struct.successor.write(oprot);
      }
      if (struct.isSetNeighbourSet()) {
        {
          oprot.writeI32(struct.neighbourSet.size());
          for (Node _iter8 : struct.neighbourSet)
          {
            _iter8.write(oprot);
          }
        }
      }
      if (struct.isSetFailedNodeSet()) {
        {
          oprot.writeI32(struct.failedNodeSet.size());
          for (Node _iter9 : struct.failedNodeSet)
          {
            _iter9.write(oprot);
          }
        }
      }
      if (struct.isSetRetryCount()) {
        oprot.writeI32(struct.retryCount);
      }
      if (struct.isSetTimeStamp()) {
        oprot.writeI64(struct.timeStamp);
      }
      if (struct.isSetSuccess()) {
        oprot.writeBool(struct.success);
      }
      if (struct.isSetResponseExpected()) {
        oprot.writeBool(struct.responseExpected);
      }
      if (struct.isSetError()) {
        oprot.writeString(struct.error);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Message struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.source = new Node();
      struct.source.read(iprot);
      struct.setSourceIsSet(true);
      struct.type = MessageType.findByValue(iprot.readI32());
      struct.setTypeIsSet(true);
      struct.lifetime = iprot.readI32();
      struct.setLifetimeIsSet(true);
      BitSet incoming = iprot.readBitSet(15);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.destination = new Node();
        struct.destination.read(iprot);
        struct.setDestinationIsSet(true);
      }
      if (incoming.get(2)) {
        struct.station = new Node();
        struct.station.read(iprot);
        struct.setStationIsSet(true);
      }
      if (incoming.get(3)) {
        struct.destinationId = iprot.readBinary();
        struct.setDestinationIdIsSet(true);
      }
      if (incoming.get(4)) {
        struct.key = iprot.readBinary();
        struct.setKeyIsSet(true);
      }
      if (incoming.get(5)) {
        struct.data = iprot.readBinary();
        struct.setDataIsSet(true);
      }
      if (incoming.get(6)) {
        struct.predecessor = new Node();
        struct.predecessor.read(iprot);
        struct.setPredecessorIsSet(true);
      }
      if (incoming.get(7)) {
        struct.successor = new Node();
        struct.successor.read(iprot);
        struct.setSuccessorIsSet(true);
      }
      if (incoming.get(8)) {
        {
          org.apache.thrift.protocol.TSet _set10 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.neighbourSet = new HashSet<Node>(2*_set10.size);
          for (int _i11 = 0; _i11 < _set10.size; ++_i11)
          {
            Node _elem12; // required
            _elem12 = new Node();
            _elem12.read(iprot);
            struct.neighbourSet.add(_elem12);
          }
        }
        struct.setNeighbourSetIsSet(true);
      }
      if (incoming.get(9)) {
        {
          org.apache.thrift.protocol.TSet _set13 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.failedNodeSet = new HashSet<Node>(2*_set13.size);
          for (int _i14 = 0; _i14 < _set13.size; ++_i14)
          {
            Node _elem15; // required
            _elem15 = new Node();
            _elem15.read(iprot);
            struct.failedNodeSet.add(_elem15);
          }
        }
        struct.setFailedNodeSetIsSet(true);
      }
      if (incoming.get(10)) {
        struct.retryCount = iprot.readI32();
        struct.setRetryCountIsSet(true);
      }
      if (incoming.get(11)) {
        struct.timeStamp = iprot.readI64();
        struct.setTimeStampIsSet(true);
      }
      if (incoming.get(12)) {
        struct.success = iprot.readBool();
        struct.setSuccessIsSet(true);
      }
      if (incoming.get(13)) {
        struct.responseExpected = iprot.readBool();
        struct.setResponseExpectedIsSet(true);
      }
      if (incoming.get(14)) {
        struct.error = iprot.readString();
        struct.setErrorIsSet(true);
      }
    }
  }

}

