/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControllerUI.java
 *
 * Created on Jan 19, 2012, 10:46:11 PM
 */
package sinchana.test;


/**
 *
 * @author Hiru
 */
public class ControllerUI extends javax.swing.JFrame implements Runnable {

	private TesterController testerController;
	private long startNodeThreadId = 0;

	/** Creates new form ControllerUI
	 * @param tc 
	 */
	public ControllerUI(TesterController tc) {
		this.testerController = tc;
		initComponents();
		setLocationRelativeTo(null);

	}

	/**
	 * 
	 * @param status
	 */
	public void setStatus(String status) {
		this.statusField.setText(status);
	}

	public void setStat(String status) {
		this.statField.setText(status);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        autoTestButtonPanel = new javax.swing.JPanel();
        startNodeSetButton = new javax.swing.JButton();
        portRange = new javax.swing.JTextField();
        numOfTesters = new javax.swing.JTextField();
        ringTestButton = new javax.swing.JButton();
        sendMessagePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        reqId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        destId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        message = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        messagePanel = new javax.swing.JPanel();
        numOfMsgsField = new javax.swing.JTextField();
        sendMsgButton = new javax.swing.JButton();
        sendMsgAutoButton = new javax.swing.JButton();
        resetAndWatchButton = new javax.swing.JButton();
        servicePanel = new javax.swing.JPanel();
        egLabel = new javax.swing.JLabel();
        dataCountTextField = new javax.swing.JTextField();
        storeButton = new javax.swing.JButton();
        retrieveButton = new javax.swing.JButton();
        removeAmountTextField = new javax.swing.JTextField();
        dataRemoveButton = new javax.swing.JButton();
        statPanel = new javax.swing.JPanel();
        statField = new javax.swing.JLabel();
        statusField = new javax.swing.JLabel();
        loggerControlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logNodeID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        logType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        logClass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        logLocation = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contatain = new javax.swing.JTextField();
        printLogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridLayout(5, 1, 0, 4));

        autoTestButtonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        startNodeSetButton.setText("Start Node Set");
        startNodeSetButton.setPreferredSize(new java.awt.Dimension(134, 24));
        startNodeSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNodeSetButtonActionPerformed(evt);
            }
        });
        autoTestButtonPanel.add(startNodeSetButton);

        portRange.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        portRange.setText("8000");
        portRange.setToolTipText("No of Testing Nodes");
        portRange.setPreferredSize(new java.awt.Dimension(96, 24));
        autoTestButtonPanel.add(portRange);

        numOfTesters.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        numOfTesters.setText("10");
        numOfTesters.setToolTipText("No of Testing Nodes");
        numOfTesters.setPreferredSize(new java.awt.Dimension(64, 24));
        autoTestButtonPanel.add(numOfTesters);

        ringTestButton.setText("Test Ring");
        ringTestButton.setEnabled(false);
        ringTestButton.setPreferredSize(new java.awt.Dimension(134, 24));
        ringTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ringTestButtonActionPerformed(evt);
            }
        });
        autoTestButtonPanel.add(ringTestButton);

        jPanel1.add(autoTestButtonPanel);

        sendMessagePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Sender");
        jLabel5.setPreferredSize(new java.awt.Dimension(56, 24));
        sendMessagePanel.add(jLabel5);

        reqId.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        reqId.setText("0");
        reqId.setPreferredSize(new java.awt.Dimension(56, 24));
        sendMessagePanel.add(reqId);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Dest:");
        jLabel6.setPreferredSize(new java.awt.Dimension(56, 24));
        sendMessagePanel.add(jLabel6);

        destId.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        destId.setText("0");
        destId.setPreferredSize(new java.awt.Dimension(56, 24));
        sendMessagePanel.add(destId);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Message");
        jLabel7.setPreferredSize(new java.awt.Dimension(72, 24));
        sendMessagePanel.add(jLabel7);

        message.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        message.setText("Where are you?");
        message.setPreferredSize(new java.awt.Dimension(96, 24));
        sendMessagePanel.add(message);

        sendButton.setText("Send");
        sendButton.setPreferredSize(new java.awt.Dimension(96, 24));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        sendMessagePanel.add(sendButton);

        jPanel1.add(sendMessagePanel);

        messagePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        numOfMsgsField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        numOfMsgsField.setText("1000");
        numOfMsgsField.setToolTipText("No of Testing Nodes");
        numOfMsgsField.setPreferredSize(new java.awt.Dimension(108, 24));
        messagePanel.add(numOfMsgsField);

        sendMsgButton.setText("Send Msg.");
        sendMsgButton.setPreferredSize(new java.awt.Dimension(134, 24));
        sendMsgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMsgButtonActionPerformed(evt);
            }
        });
        messagePanel.add(sendMsgButton);

        sendMsgAutoButton.setText("Send Continuesly");
        sendMsgAutoButton.setPreferredSize(new java.awt.Dimension(134, 24));
        sendMsgAutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMsgAutoButtonActionPerformed(evt);
            }
        });
        messagePanel.add(sendMsgAutoButton);

        resetAndWatchButton.setText("Reset & Watch");
        resetAndWatchButton.setPreferredSize(new java.awt.Dimension(134, 24));
        resetAndWatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAndWatchButtonActionPerformed(evt);
            }
        });
        messagePanel.add(resetAndWatchButton);

        jPanel1.add(messagePanel);

        servicePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        egLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        egLabel.setText("No.of Data");
        egLabel.setPreferredSize(new java.awt.Dimension(60, 24));
        servicePanel.add(egLabel);

        dataCountTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        dataCountTextField.setText("50");
        dataCountTextField.setToolTipText("No of Auto Testing Nodes");
        dataCountTextField.setPreferredSize(new java.awt.Dimension(32, 24));
        servicePanel.add(dataCountTextField);

        storeButton.setText("Store");
        storeButton.setPreferredSize(new java.awt.Dimension(65, 24));
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });
        servicePanel.add(storeButton);

        retrieveButton.setText("Retrieve");
        retrieveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveButtonActionPerformed(evt);
            }
        });
        servicePanel.add(retrieveButton);

        removeAmountTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        removeAmountTextField.setText("20");
        removeAmountTextField.setPreferredSize(new java.awt.Dimension(32, 24));
        servicePanel.add(removeAmountTextField);

        dataRemoveButton.setText("Remove");
        dataRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataRemoveButtonActionPerformed(evt);
            }
        });
        servicePanel.add(dataRemoveButton);

        jPanel1.add(servicePanel);

        statPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        statField.setText("Stat");
        statField.setPreferredSize(new java.awt.Dimension(520, 24));
        statPanel.add(statField);

        jPanel1.add(statPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        statusField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusField.setText("Status...");
        statusField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(statusField, gridBagConstraints);

        loggerControlPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Node ID");
        jLabel1.setPreferredSize(new java.awt.Dimension(48, 20));
        loggerControlPanel.add(jLabel1);

        logNodeID.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        logNodeID.setPreferredSize(new java.awt.Dimension(32, 20));
        loggerControlPanel.add(logNodeID);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Type");
        jLabel2.setPreferredSize(new java.awt.Dimension(32, 20));
        loggerControlPanel.add(jLabel2);

        logType.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        logType.setPreferredSize(new java.awt.Dimension(32, 20));
        loggerControlPanel.add(logType);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Class");
        jLabel3.setPreferredSize(new java.awt.Dimension(36, 20));
        loggerControlPanel.add(jLabel3);

        logClass.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        logClass.setText("7");
        logClass.setPreferredSize(new java.awt.Dimension(32, 20));
        logClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logClassActionPerformed(evt);
            }
        });
        loggerControlPanel.add(logClass);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Location");
        jLabel4.setPreferredSize(new java.awt.Dimension(52, 20));
        loggerControlPanel.add(jLabel4);

        logLocation.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        logLocation.setText("0");
        logLocation.setPreferredSize(new java.awt.Dimension(32, 20));
        loggerControlPanel.add(logLocation);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Contaions");
        jLabel9.setPreferredSize(new java.awt.Dimension(52, 20));
        loggerControlPanel.add(jLabel9);

        contatain.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        contatain.setPreferredSize(new java.awt.Dimension(64, 20));
        loggerControlPanel.add(contatain);

        printLogButton.setText("Print");
        printLogButton.setPreferredSize(new java.awt.Dimension(64, 24));
        printLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLogButtonActionPerformed(evt);
            }
        });
        loggerControlPanel.add(printLogButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(loggerControlPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
//		testerController.send(message.getText(), this.destId.getText(), this.reqId.getText());
//                testerController.publishService(10);
//	testerController.storeData();
}//GEN-LAST:event_sendButtonActionPerformed

private void startNodeSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNodeSetButtonActionPerformed
	Thread thread = new Thread(this);
	this.startNodeThreadId = thread.getId();
	thread.start();
	this.ringTestButton.setEnabled(true);
}//GEN-LAST:event_startNodeSetButtonActionPerformed

private void ringTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ringTestButtonActionPerformed

	testerController.startRingTest();

}//GEN-LAST:event_ringTestButtonActionPerformed

private void printLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLogButtonActionPerformed

	testerController.printLogs(
			this.logNodeID.getText(),
			this.logType.getText(),
			this.logClass.getText(),
			this.logLocation.getText(),
			this.contatain.getText());

}//GEN-LAST:event_printLogButtonActionPerformed

private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeButtonActionPerformed
	testerController.storeData(Integer.parseInt(dataCountTextField.getText()));

}//GEN-LAST:event_storeButtonActionPerformed

private void retrieveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveButtonActionPerformed
	testerController.retrieveData();
}//GEN-LAST:event_retrieveButtonActionPerformed

private void dataRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataRemoveButtonActionPerformed
	testerController.removeData(Integer.parseInt(removeAmountTextField.getText()));
}//GEN-LAST:event_dataRemoveButtonActionPerformed

private void logClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logClassActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_logClassActionPerformed

private void resetAndWatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAndWatchButtonActionPerformed

	testerController.resetAndWatch();
}//GEN-LAST:event_resetAndWatchButtonActionPerformed

private void sendMsgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMsgButtonActionPerformed

	testerController.test(Long.parseLong(this.numOfMsgsField.getText()));
}//GEN-LAST:event_sendMsgButtonActionPerformed

private void sendMsgAutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMsgAutoButtonActionPerformed

	testerController.startAutoTest(Long.parseLong(this.numOfMsgsField.getText()));
}//GEN-LAST:event_sendMsgAutoButtonActionPerformed
	/**
	 * @param args the command line arguments
	 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel autoTestButtonPanel;
    private javax.swing.JTextField contatain;
    private javax.swing.JTextField dataCountTextField;
    private javax.swing.JButton dataRemoveButton;
    private javax.swing.JTextField destId;
    private javax.swing.JLabel egLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField logClass;
    private javax.swing.JTextField logLocation;
    private javax.swing.JTextField logNodeID;
    private javax.swing.JTextField logType;
    private javax.swing.JPanel loggerControlPanel;
    private javax.swing.JTextField message;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextField numOfMsgsField;
    private javax.swing.JTextField numOfTesters;
    private javax.swing.JTextField portRange;
    private javax.swing.JButton printLogButton;
    private javax.swing.JTextField removeAmountTextField;
    private javax.swing.JTextField reqId;
    private javax.swing.JButton resetAndWatchButton;
    private javax.swing.JButton retrieveButton;
    private javax.swing.JButton ringTestButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JPanel sendMessagePanel;
    private javax.swing.JButton sendMsgAutoButton;
    private javax.swing.JButton sendMsgButton;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JButton startNodeSetButton;
    private javax.swing.JLabel statField;
    private javax.swing.JPanel statPanel;
    private javax.swing.JLabel statusField;
    private javax.swing.JButton storeButton;
    // End of variables declaration//GEN-END:variables

	@Override
	public void run() {
		if (Thread.currentThread().getId() == this.startNodeThreadId) {
			testerController.startNodeSet(Integer.parseInt(this.portRange.getText()),
					Integer.parseInt(this.numOfTesters.getText()));
		}
	}
}
